### ISSUE TITLE
You are running a development build of vue-i18n

### ISSUE THREAD

**Issue by scambier** [intlify/vite-plugin-vue-i18n#74]
**Module versions (please complete the following information):**
 - `vue`: ^3.0.4
 - `vue-i18n`: ^9.0.0

Hello, I can't get rid of the following warnings after building my app:
- `You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.`
- `You are running a development build of vue-i18n.
Make sure to use the production build (*.prod.js) when deploying for production.`

I'm using Vue 3 with Vite 2, and my locale files are in yaml (there is no . `NODE_ENV` is set to `production`. I heavily use `$t()` in single-page components, have some calls to `useI18n()`, but don't use the `<i18n>` block at all.

I tried using `@intlify/vite-plugin-vue-i18n` in my `vite.config.ts`, but without success.
```ts
import vue from '@vitejs/plugin-vue'
import vueI18n from '@intlify/vite-plugin-vue-i18n'

const config:= {
  plugins: [
    vue(),
    vueI18n({
      // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
      compositionOnly: false,

      // you need to set i18n resource including paths !
      include: path.resolve(__dirname, './src/locales/**')
    }),
```

It's quite certainly a comprehension problem on my part

**Comment by kazupon** [comment]
I've just fixed it!
please check lastest version!
https://github.com/intlify/vite-plugin-vue-i18n/releases/tag/v2.0.2

**Comment by scambier** [comment]
@kazupon 
Hello, I still have a message "_You are running a development build of vue-i18n. Make sure to use the production build (*.prod.js) when deploying for production._" unless I make a build in `production` mode.

To reproduce, simple build your app with `vite build --mode somethingThatIsntProduction`, even if the corresponding mode specifies `NODE_ENV=production`.

Like I said in [this post](https://github.com/intlify/vite-plugin-vue-i18n/issues/74#issuecomment-796579848), my comprehension is that the build mode name should be irrelevant, and the only value that should determine if a build is for production or not should be `NODE_ENV`. In my use-case, I make builds for a staging environment that has to be indistinguishable from production.

**Comment by kazupon** [comment]
@scambier 
Thank you for your reporting!
This is a bug of vue-i18n and vite-plugin-vue-i18n.
https://github.com/intlify/vite-plugin-vue-i18n/pull/80
https://github.com/intlify/vue-i18n-next/pull/404

We are going to release vue-i18n v9.1 soon.
please wait the release publish. 🙏

**Comment by kazupon** [comment]
I released vue-i18n v9.1 !
latest version is v9.1.2

You can try it! :)

**Comment by scambier** [comment]
@kazupon There's still a warning.

> You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.

My locale files are .json.

vite.config.js:
```
const config: UserConfig = {
  plugins: [
    vue(),
    vueI18n({
      runtimeOnly: false,
      // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
      compositionOnly: false,

      // you need to set i18n resource including paths !
      include: resolve(__dirname, './src/locales/**')
    }),
```

`NODE_ENV=production` for the build

**Comment by kazupon** [comment]
Hmm, it's strange … 🤔 
Your vite.config.js is also correct.

I checked at vue-i18n starter for vite.
I could not reproduce it.
https://github.com/intlify/vite-vue-i18n-starter

**Comment by Miguel-Bento-Github** [comment]
@kazupon I'm not sure if this helps but I also have this issue on a standard Vue project.

All I did in my project that was scaffolded by using @vue/cli
Steps:
- Run `vue create app-name`
- Use manual setup
- Choose vue 3
After the installation run
- `vue add i18n`

Locales folder doesn't work and I get that in my console.

![Screenshot 2021-06-03 at 14 08 50](https://user-images.githubusercontent.com/51338450/120642486-3a1b0880-c475-11eb-9132-6504b5520ed1.png)

**Comment by Miguel-Bento-Github** [comment]
In vue.config.js the localeDir is set to `'locales'`, my solution here was to change that with `'@/locales/'`
```
# vue.config.js
...
pluginOptions: {
    i18n: {
      locale: "en",
      fallbackLocale: "en",
      **localeDir: "@/locales",**
      enableLegacy: true,
      runtimeOnly: false,
      fullInstall: true,
    },
  },
```
